[package]
name = "query-engine-napi"
version = "0.1.0"
authors = ["Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
vendored-openssl = ["sql-connector/vendored-openssl"]

[dependencies]
query-core = { path = "../core" }
request-handlers = { path = "../request-handlers" }
query-connector = { path = "../connectors/query-connector" }
user-facing-errors = { path = "../../libs/user-facing-errors" }
datamodel = { path = "../../libs/datamodel/core" }
sql-connector = { path = "../connectors/sql-query-connector", package = "sql-query-connector" }
prisma-models = { path = "../../libs/prisma-models" }
napi = { version = "1.3.4", default-features = false, features = ["napi4", "tokio_rt", "serde-json"] }
napi-derive = "1"
thiserror = "1"
connection-string = "0.1"
url = "2"
serde_json = { version = "1", features = ["preserve_order", "float_roundtrip"] }
serde = "1"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
tracing-opentelemetry = "0.11"
datamodel-connector = { path = "../../libs/datamodel/connectors/datamodel-connector" }
opentelemetry = "0.12"
opentelemetry-otlp = { version = "0.5", features = ["tls", "tls-roots"] }
tokio = { version = "1", features = ["sync"] }
enumflags2 = "0.6"

[build-dependencies]
napi-build = "1"
