[package]
name = "query-connector"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
once_cell = "1.3"
prisma-models = { path = "../../../libs/prisma-models" }
prisma-value = { path = "../../../libs/prisma-value" }
thiserror = "1.0"
uuid = "0.8"
itertools = "0.8"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
user-facing-errors = { path = "../../../libs/user-facing-errors" }
async-trait = "0.1.31"
